"""ML model evaluation API routes."""

import json
from pathlib import Path

import structlog
from fastapi import APIRouter, Depends, HTTPException, Request, status

from app.config import settings
from app.utils.rate_limiter import limiter
from app.utils.security import get_current_user

logger = structlog.stdlib.get_logger()

router = APIRouter(prefix="/api/ml", tags=["ML"])


@router.get("/evaluation")
@limiter.limit("30/minute")
def get_evaluation_report(request: Request, current_user=Depends(get_current_user)):
    """Return the model evaluation report (confusion matrix, classification metrics).

    Reads the evaluation_report.json generated by the training pipeline.
    Returns 404 if no report has been generated yet.
    """
    eval_path = Path(settings.MODEL_DIR) / "evaluation" / "evaluation_report.json"
    if not eval_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No evaluation report available",
        )

    try:
        with open(eval_path) as f:
            report = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        logger.error("failed_to_read_evaluation_report", error=str(exc), path=str(eval_path))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to read evaluation report",
        )

    return report
