"use client";

import { Suspense, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import toast from "react-hot-toast";
import Cookies from "js-cookie";
import { authApi, extractErrorMessage } from "@/lib/api";
import { useAuth } from "@/context/AuthContext";

/**
 * Tenant-invite acceptance page.
 *
 * Lands here from a `${FRONTEND_URL}/accept-invite?token=<JWT>` link
 * generated by services.invitation_service when an admin or
 * compliance_head adds a team member by email. The invitee chooses a
 * password; the backend sets it + activates the account + returns the
 * standard access + refresh token pair. The user is then redirected
 * straight to /dashboard.
 *
 * No pre-validation of the token: the backend rejects expired / wrong
 * type / already-accepted tokens with a 400 + an actionable message,
 * and the same code path also enforces password strength server-side.
 */
function AcceptInviteInner() {
    const router = useRouter();
    const params = useSearchParams();
    const token = params.get("token") || "";
    const { setTokensFromOAuth } = useAuth();
    const [password, setPassword] = useState("");
    const [confirm, setConfirm] = useState("");
    const [submitting, setSubmitting] = useState(false);
    const [lengthError, setLengthError] = useState("");
    const [mismatchError, setMismatchError] = useState("");

    const focusRing = "focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--accent)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg-page)]";
    const inputClass = "w-full px-3 h-10 bg-[var(--bg-page)] border border-[var(--border-emphasis)] rounded-md text-[13px] text-[var(--text-primary)] placeholder:text-[var(--text-disabled)] transition-colors focus:outline-none focus:border-[var(--accent)] focus-visible:ring-2 focus-visible:ring-[var(--accent)]/50 focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--bg-elevated)]";

    if (!token) {
        return (
            <div className="min-h-screen flex items-center justify-center p-6 bg-[var(--bg-page)]">
                <div className="max-w-sm w-full text-center space-y-3">
                    <h1 className="text-lg font-semibold text-[var(--text-primary)]">
                        Invitation link missing token
                    </h1>
                    <p className="text-sm text-[var(--text-muted)]">
                        Open the link from the invitation email exactly as it
                        was sent. If you no longer have it, ask the person who
                        invited you to send a new invitation.
                    </p>
                    <Link
                        href="/login"
                        className={`inline-block px-3 h-10 leading-10 rounded-md bg-[var(--accent)] text-white text-sm font-medium hover:bg-[var(--accent-strong)] transition-colors ${focusRing}`}
                    >
                        Go to sign in
                    </Link>
                </div>
            </div>
        );
    }

    const submit = async () => {
        setLengthError("");
        setMismatchError("");
        if (password.length < 12) {
            setLengthError("Password must be at least 12 characters");
            return;
        }
        if (password !== confirm) {
            setMismatchError("Passwords do not match");
            return;
        }
        setSubmitting(true);
        try {
            const res = await authApi.acceptInvite({ token, password });
            const { access_token, refresh_token, user } = res.data;
            // Mirror the cookie+context wiring that AuthContext.login does
            // so the rest of the app sees an authenticated session.
            const secure = process.env.NODE_ENV === "production";
            Cookies.set("token", access_token, {
                sameSite: "Strict",
                secure,
                expires: 1 / 48,
            });
            Cookies.set("refresh_token", refresh_token, {
                sameSite: "Strict",
                secure,
                expires: 7,
            });
            Cookies.set("user", JSON.stringify(user), {
                sameSite: "Strict",
                secure,
                expires: 7,
            });
            setTokensFromOAuth(access_token, refresh_token, user);
            toast.success("Welcome! You are signed in.");
            router.replace("/dashboard");
        } catch (err) {
            toast.error(
                extractErrorMessage(err, "Could not accept invitation"),
            );
        } finally {
            setSubmitting(false);
        }
    };

    return (
        <div className="min-h-screen flex items-center justify-center p-6 bg-[var(--bg-page)]">
            <form
                onSubmit={(e) => {
                    e.preventDefault();
                    submit();
                }}
                aria-busy={submitting}
                className="surface-card max-w-sm w-full space-y-5 p-6"
            >
                <div className="space-y-1">
                    <h1 className="text-lg font-semibold text-[var(--text-primary)]">
                        Set your password
                    </h1>
                    <p className="text-sm text-[var(--text-muted)]">
                        You were invited to a TaxSync workspace. Choose a
                        password to finish setting up your account and sign in.
                    </p>
                </div>
                <div>
                    <label
                        htmlFor="accept-invite-password"
                        className="text-xs font-medium text-[var(--text-muted)] mb-1.5 block"
                    >
                        Password
                    </label>
                    <input
                        id="accept-invite-password"
                        type="password"
                        autoComplete="new-password"
                        value={password}
                        onChange={(e) => {
                            setPassword(e.target.value);
                            if (lengthError) setLengthError("");
                        }}
                        minLength={12}
                        aria-invalid={lengthError ? true : undefined}
                        aria-describedby="accept-invite-password-help"
                        className={inputClass}
                    />
                    {lengthError ? (
                        <p id="accept-invite-password-help" role="alert" className="text-[12px] text-[var(--danger)] mt-1">
                            {lengthError}
                        </p>
                    ) : (
                        <p id="accept-invite-password-help" className="text-[11px] text-[var(--text-muted)] mt-1">
                            Minimum 12 characters.
                        </p>
                    )}
                </div>
                <div>
                    <label
                        htmlFor="accept-invite-confirm"
                        className="text-xs font-medium text-[var(--text-muted)] mb-1.5 block"
                    >
                        Confirm password
                    </label>
                    <input
                        id="accept-invite-confirm"
                        type="password"
                        autoComplete="new-password"
                        value={confirm}
                        onChange={(e) => {
                            setConfirm(e.target.value);
                            if (mismatchError) setMismatchError("");
                        }}
                        minLength={12}
                        aria-invalid={mismatchError ? true : undefined}
                        aria-describedby={mismatchError ? "accept-invite-confirm-error" : undefined}
                        className={inputClass}
                    />
                    {mismatchError && (
                        <p id="accept-invite-confirm-error" role="alert" className="text-[12px] text-[var(--danger)] mt-1">
                            {mismatchError}
                        </p>
                    )}
                </div>
                <button
                    type="submit"
                    disabled={submitting}
                    className={`w-full h-10 rounded-md bg-[var(--accent)] text-white text-sm font-medium hover:bg-[var(--accent-strong)] transition-colors disabled:opacity-60 disabled:cursor-not-allowed ${focusRing}`}
                >
                    {submitting ? "Setting password…" : "Set password and sign in"}
                </button>
            </form>
        </div>
    );
}

export default function AcceptInvitePage() {
    return (
        <Suspense fallback={null}>
            <AcceptInviteInner />
        </Suspense>
    );
}
